#!/bin/bash 

# Add user
sudo useradd -mG sudo -p password msmet

# Install software
sudo yum update -y
sudo yum install curl vim ca-certificates
sudo yum remove awscli
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
unzip awscliv2.zip
sudo ./aws/install

# Allow no key connection
sudo sed -i 's/#PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
sudo systemctl restart sshd
